### ISSUE TITLE
Expose Cons(..)

### ISSUE THREAD

**Issue by aslakg** [hrldcpr/elm-cons#3]
Hi,

your library is very nice and useful - but one thing makes it harder to use than necessary - it exports Cons but not Cons(..)
That means I can't pattern match on a Cons , and also I can't initialize data structures from those I've printed with toString.

**Comment by blaineylab** [comment]
+1 this suggestion 

any hope you can bump this to Elm 0.19 as well?

**Comment by hrldcpr** [comment]
Thanks, I'll look into this. I recall the Elm "best practices" saying to avoid exposing constructors, but I don't remember why…

(I also made a separate issue for 0.19 support — #4)

**Comment by blaineylab** [comment]
I think not exposing the constructor makes it possible to change the implementation without a new major version. But maybe in this case the implementation is pretty solid.

**Comment by hrldcpr** [comment]
Yeah good point, this is a very simple data structure / unlikely to change. And since at least 2 people would like the constructor exposed, I think that's good enough for me :)

I'll make a new release soon.

**Comment by hrldcpr** [comment]
The constructor is exposed as of elm-cons v3.0.0 🎉
